In [2]:
import numpy as np
sh=pd.array([[104,177,189,156,121,126],[146,131,178,193,190,125],[152,106,109,168,174,143],[178,130,189,164,133,156]])
sh

array([[104, 177, 189, 156, 121, 126],
       [146, 131, 178, 193, 190, 125],
       [152, 106, 109, 168, 174, 143],
       [178, 130, 189, 164, 133, 156]])

In [36]:
sh[[0],[2]]

array([189])

In [30]:
sh[:,(1,2,5)]

array([[177, 189, 126],
       [131, 178, 125],
       [106, 109, 156],
       [130, 189, 156]])

In [31]:
sh[(0,1),(0,1)]

array([104, 131])

In [44]:
sh[[[0],[2]],[1,2,5]]

array([[177, 189, 126],
       [106, 109, 156]])

In [47]:
sh[[[0]],[1,2,5]]

array([[177, 189, 126]])

In [61]:
月销量=np.sum(sh,axis=0)
月销量

array([580, 544, 665, 681, 618, 550])

In [63]:
列号=np.where(月销量<600)
列号[0]

array([0, 1, 5])

In [64]:
sh[:,列号[0]]

array([[104, 177, 126],
       [146, 131, 125],
       [152, 106, 143],
       [178, 130, 156]])

In [3]:
上海+深圳

NameError: name '上海' is not defined